window.pledges = [
  { id: 201, first: "Aaron", last: "Coley", hometown: "Trenton, NJ - 2027", major: "BME", image: "" },
  { id: 202, first: "Albert", last: "Liu", hometown: "San Diego, CA - 2027", major: "Biology/CS", image: "" },
  { id: 203, first: "Alex", middle: "Constantine", last: "Christ", hometown: "McLean, VA - 2027", major: "BME", image: "" },
  { id: 204, first: "Andrew", last: "Spong", hometown: "2026", major: "", image: "" },
  { id: 205, first: "Avery", middle: "Connor", last: "Estopinal", hometown: "Nashville, TN - 2026", major: "ME", image: "" },
  { id: 206, first: "Brian", middle: "S.", last: "Yoon", hometown: "Hawthorn Woods, IL - 2027", major: "Chemistry", image: "" },
  { id: 207, first: "Ciaran", middle: "James", last: "Burr", hometown: "Waxhaw, NC - 2027", major: "CS/Stat", image: "" },
  { id: 208, first: "Colin", middle: "Daniel", last: "Miley", hometown: "Avon, CT - 2027", major: "Econ", image: "" },
  { id: 209, first: "Declan", middle: "William", last: "Hall", hometown: "Martinsburg, WV - 2027", major: "Econ", image: "" },
  { id: 210, first: "Eddie", last: "Zhou", hometown: "Sammamish, WA - 2027", major: "CSus", image: "" },
  { id: 211, first: "Gavin", middle: "Richard", last: "Burns", hometown: "Garden City, NY - 2027", major: "Econ/Stat", image: "" },
  { id: 212, first: "Hunter", middle: "Zach", last: "Newsome", hometown: "Atlanta, GA - 2027", major: "ECE/CS", image: "" },
  { id: 213, first: "Jake", middle: "Ramon", last: "Fernandez", hometown: "Atlanta, GA - 2027", major: "Biology", image: "" },
  { id: 214, first: "Jerry", last: "Liu", hometown: "Seattle, WA - 2027", major: "Biology", image: "" },
  { id: 215, first: "Josh", middle: "Henry", last: "Coutu", hometown: "Oakland, CA - 2027", major: "ME", image: "" },
  { id: 216, first: "Justin", last: "Cockerham", hometown: "Philadelphia, PA - 2027", major: "Econ/Pub Pol", image: "" },
  { id: 217, first: "Kiran", last: "Pathy", hometown: "Madison, CT - 2027", major: "Pub Pol", image: "" },
  { id: 218, first: "Kyle", middle: "Yian", last: "Burgess", hometown: "Raleigh, NC - 2027", major: "ME", image: "" },
  { id: 219, first: "Kyle", middle: "Patrick", last: "Black", hometown: "Arlington, VA - 2027", major: "Pub Pol/Spanish", image: "" },
  { id: 220, first: "Linden", middle: "Everett", last: "Ambrose", hometown: "Blacksburg, VA - 2027", major: "BME", image: "" },
  { id: 221, first: "Nathaniel", middle: "David", last: "Corey", hometown: "Baltimore, MD - 2027", major: "ECE", image: "" },
  { id: 222, first: "Parker", middle: "John", last: "Miles", hometown: "Atlanta, GA - 2027", major: "Econ", image: "" },
  { id: 223, first: "Riley", middle: "Nims", last: "Cusick", hometown: "New York, NY - 2027", major: "ECE/CS", image: "" },
  { id: 224, first: "Ryan", last: "Yu", hometown: "Long Island, New York - 2027", major: "Econ/Stat", image: "" },
  { id: 225, first: "Ryyan", middle: "Mahtani", last: "Siddiqi", hometown: "Newport Beach, CA - 2027", major: "Econ", image: "" },
  { id: 226, first: "Salvador", middle: "Padilla", last: "Katz", hometown: "Newport, RI - 2027", major: "Econ/Psych", image: "" },
  { id: 227, first: "Siddarth", middle: "Vallabh", last: "Das", hometown: "Houston, TX - 2027", major: "BME", image: "" },
  { id: 228, first: "Wiley", middle: "Joseph", last: "Thornton", hometown: "Naples, FL - 2027", major: "ECE", image: "" },
  { id: 229, first: "William", middle: "Richard", last: "McCune", hometown: "Martinsburg, WV - 2027", major: "CS", image: "" },
  { id: 230, first: "Zachary", middle: "Marshall", last: "Robers", hometown: "Chapel Hill, NC - 2027", major: "Math", image: "" },
];