window.pledges = [
  { id: 301, first: "Andrew", last: "Huang", hometown: "Athens, OH - 2026", major: "CS", image: "" },
  { id: 302, first: "Brian", middle: "Andrew", last: "Negus", hometown: "Chattanooga, TN - 2026", major: "Econ", image: "" },
  { id: 303, first: "Braxton", middle: "Joseph", last: "LaNois", hometown: "Melbourne, FL - 2026", major: "Philosophy & CS", image: "" },
  { id: 304, first: "Charlie", middle: "Thomas", last: "Konen", hometown: "Sugar Grove, IL - 2026", major: "Data Science IDM", image: "" },
  { id: 305, first: "Christian", middle: "Braden", last: "Ellis", hometown: "Aledo, TX - 2026", major: "Classics/ Econ", image: "" },
  { id: 306, first: "Daniel", middle: "Jacob", last: "Cohen", hometown: "Fort Lauderdale, FL - 2026", major: "Econ", image: "" },
  { id: 307, first: "Davis", middle: "Charles", last: "Featherstone", hometown: "Tipp City, OH - 2026", major: "Econ", image: "" },
  { id: 308, first: "Devin", middle: "Patrick", last: "Mulcrone", hometown: "Vernon Hills, IL - 2026", major: "Philosophy", image: "" },
  { id: 309, first: "Ethan", middle: "Daiwei", last: "Shang", hometown: "Chapel Hill, NC - 2026", major: "Econ/Stat", image: "" },
  { id: 310, first: "Gage", middle: "Velez", last: "Garcia", hometown: "Los Altos, CA - 2026", major: "CS", image: "" },
  { id: 311, first: "Garrett", middle: "August", last: "Cronk", hometown: "Charlotte, NC - 2026", major: "Econ", image: "" },
  { id: 312, first: "Gilbert", middle: "Steven", last: "Rosario-Acevedo", hometown: "Freeport, NY - 2026", major: "Chem/Bio", image: "" },
  { id: 313, first: "Ian", middle: "Clarke", last: "McPherson", hometown: "New Park, PA - 2026", major: "Econ", image: "" },
  { id: 314, first: "Jake", middle: "Walter", last: "Wolfram", hometown: "Cary, NC - 2026", major: "Physics", image: "" },
  { id: 315, first: "Jonathan", middle: "Heng", last: "Ding", hometown: "Roseland, NJ - 2026", major: "Psych", image: "" },
  { id: 316, first: "Kethan", middle: "Sai", last: "Poduri", hometown: "Ashburn, VA - 2026", major: "CS/Stat", image: "" },
  { id: 317, first: "Maxwell", middle: "Winston", last: "Jewell", hometown: "Boise, ID - 2026", major: "Physics", image: "" },
  { id: 318, first: "Palo", middle: "Diego", last: "Silva", hometown: "Palo Alto, CA - 2026", major: "ECE/CS", image: "" },
  { id: 319, first: "Peter", middle: "Robert Laney", last: "Lopez", hometown: "Orlando, FL - 2026", major: "ECE", image: "" },
  { id: 320, first: "Yash", last: "Gangavarapu", hometown: "Vernon Hills, IL - 2026", major: "ECE/CS", image: "" },
];
